parameters:
    webinar_account.invoice.class:                  Webinar\Bundle\AccountBundle\Entity\Invoice
    webinar_account.invoice.form_type.class:        Webinar\Bundle\AccountBundle\Form\InvoiceType
    webinar_account.invoice.form_type.api.class:    Webinar\Bundle\AccountBundle\Form\InvoiceApiType
    webinar_account.invoice.form.handler.class:     Webinar\Bundle\AccountBundle\Form\InvoiceHandler
    webinar_account.manager.api.class:              Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    # Form types
    webinar_account.invoice.form_type:
        class: %webinar_account.invoice.form_type.class%
        tags:
            - { name: form.type, alias: webinar_accountbundle_invoice }

    webinar_account.invoice.form_type.api:
        class: %webinar_account.invoice.form_type.api.class%
        tags:
            - { name: form.type, alias: webinar_accountbundle_invoice_api }

    # Forms
    webinar_account.invoice.form:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "webinar_accountbundle_invoice_form"
            - "webinar_accountbundle_invoice"

    webinar_account.invoice.form.api:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "invoice"
            - "webinar_accountbundle_invoice_api"

    # Form Handlers
    webinar_account.invoice.form.handler:
        class: %webinar_account.invoice.form.handler.class%
        scope: request
        arguments:
            - @webinar_account.invoice.form
            - @request
            - @doctrine.orm.entity_manager

    webinar_account.invoice.form.handler.api:
        class: %webinar_account.invoice.form.handler.class%
        scope: request
        arguments:
            - @webinar_account.invoice.form.api
            - @request
            - @doctrine.orm.entity_manager

    # Manager
    webinar_account.invoice_manager.api:
        class: %webinar_account.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %webinar_account.invoice.class%
            - @doctrine.orm.entity_manager

