Webinar\Bundle\AccountBundle\Entity\Invoice:
    properties:
        total:
            - NotBlank:     ~
        note:
            - NotBlank:     ~
            - Length:
                min:        3
                max:        255

OroCRM\Bundle\AccountBundle\Entity\Account:
    properties:
        name:
            - NotBlank:     { groups: [invoiced_account] }
            - Length:
                min:        10
                max:        255
                groups:     [invoiced_account]
        organization:
            - NotBlank:     { groups: [invoiced_account] }
        invoice:
            - NotBlank:     { groups: [invoiced_account] }

