Webinar\Bundle\AccountBundle\Entity\Invoice:
    properties:
        total:
            - NotBlank:     ~
        note:
            - NotBlank:     ~
            - Length:
                min:        3
                max:        255

OroCRM\Bundle\AccountBundle\Entity\Account:
    properties:
        name:
            - NotBlank:     ~
            - Length:
                min:        3
                max:        255
        organization:
            - NotBlank:     ~

        invoice:
            - NotBlank:     { groups: [invoiced_account] }

OroCRM\Bundle\ContactBundle\Entity\ContactAddress:
    properties:
        street:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
    constraints:
        - Callback:
            methods: [isRegionValid]
