datagrid:
    ticket-grid:
        source:
            type: orm
            acl_resource: webinar_demo_ticket_view
            query:
                select:
                    #- t.id
                    #- t.name
                    # ... or
                    - t
                from:
                    - { table: %webinar_demo.ticket.class%, alias: t }
#                join:
#                    left:
#                        - { join: o.contact , alias: contact }
        columns:
            seatNum:
                label:         webinar.ticket.form.seat_num.label
            description:
                label:         webinar.ticket.form.description.label
            eventName:
                label:         webinar.ticket.form.event_name.label
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            eventDate:
                label:         webinar.ticket.form.event_date.label
                frontend_type: date
        properties:
            id: ~
            view_link:
                type:       url
                route:      webinar_demo_ticket_view
                params:     [ id ]
            update_link:
                type:       url
                route:      webinar_demo_ticket_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      webinar_api_delete_ticket
                params:     [ id ]
        sorters:
            columns:
                seatNum:
                    data_name: t.seatNum
                description:
                    data_name: t.description
                eventName:
                    data_name: t.event_name
                createdAt:
                    data_name: t.createdAt
                eventDate:
                    data_name: t.eventDate
            default:
                createdAt: DESC
        filters:
            columns:
                seatNum:
                    type: string
                    data_name: t.seatNum
                description:
                    type: string
                    data_name: t.description
                eventName:
                    type: string
                    data_name: t.eventName
                createdAt:
                    type: datetime
                    data_name: t.createdAt
                eventDate:
                    type: date
                    data_name: t.eventDate
        actions:
            view:
                type:          navigate
                acl_resource:  webinar_demo_ticket_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  webinar_demo_ticket_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  webinar_demo_ticket_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
