parameters:
    webinar_demo.ticket.class:                  Webinar\Bundle\DemoBundle\Entity\Ticket
    webinar_demo.ticket.form_type.class:        Webinar\Bundle\DemoBundle\Form\TicketType
    webinar_demo.ticket.form_type.api.class:    Webinar\Bundle\DemoBundle\Form\TicketApiType
    webinar_demo.ticket.form.handler.class:     Webinar\Bundle\DemoBundle\Form\TicketHandler
    webinar_demo.manager.api.class:             Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    # override crm listener
    orocrm_contact.subscriber.contact_listener.class:                     Webinar\Bundle\DemoBundle\EventListener\ContactListener

    # Form types
    webinar_demo.ticket.form_type:
        class: %webinar_demo.ticket.form_type.class%
        tags:
            - { name: form.type, alias: webinar_demobundle_ticket }

    webinar_demo.ticket.form_type.api:
        class: %webinar_demo.ticket.form_type.api.class%
        tags:
            - { name: form.type, alias: webinar_demobundle_ticket_api }

    # Forms
    webinar_demo.ticket.form:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "webinar_demobundle_ticket_form"
            - "webinar_demobundle_ticket"

    webinar_demo.ticket.form.api:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "ticket"
            - "webinar_demobundle_ticket_api"

    # Form handlers
    webinar_demo.ticket.form.handler:
        class: %webinar_demo.ticket.form.handler.class%
        scope: request
        arguments:
            - @webinar_demo.ticket.form
            - @request
            - @doctrine.orm.entity_manager

    webinar_demo.ticket.form.handler.api:
        class: %webinar_demo.ticket.form.handler.class%
        scope: request
        arguments:
            - @webinar_demo.ticket.form.api
            - @request
            - @doctrine.orm.entity_manager

    # API Manager
    webinar_demo.ticket_manager.api:
        class: %webinar_demo.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %webinar_demo.ticket.class%
            - @doctrine.orm.entity_manager
