webinar_demo_bundle:
    resource: "@WebinarDemoBundle/Controller"
    type:     annotation
    prefix:   /

webinar_demo_api_ticket:
    resource:     "@WebinarDemoBundle/Controller/Api/Rest/TicketController.php"
    type:         rest
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
    defaults:
        version:  latest