datagrid:
    # partner accounts grid
    partner-accounts-grid:
        extended_entity_name: %orocrm_partner.partner.entity.class%
        source:
            type: orm
            acl_resource: orocrm_partner_view
            query:
                select:
                    - partner.id
                    - account.name
                    - account.createdAt
                    - account.updatedAt
                    - partner.startDate as startDate
                    - partner.partnerCondition as condition
                    - partnerStatus.label as status
                    - CONCAT(partnerOwner.firstName, CONCAT(' ', partnerOwner.lastName)) as ownerName
                from:
                    - { table: OroCRMPartnerBundle:Partner, alias: partner }
                join:
                    left:
                        - { join: partner.account, alias: account }
                        - { join: partner.owner, alias: partnerOwner }
                        - { join: partner.status, alias: partnerStatus }
        columns:
            name:
                label:   orocrm.account.name.label
            startDate:
                label:   orocrm.partner.start_date.label
                frontend_type: datetime
            condition:
                label:   orocrm.partner.partner_condition.label
                frontend_type: string
            status:
                label:   orocrm.partner.status.label
                frontend_type: string
            ownerName:
                label:   orocrm.partner.owner.label
            createdAt:
                label:   orocrm.partner.account.created_at.label
                frontend_type: datetime
            updatedAt:
                label:   orocrm.partner.account.updated_at.label
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_partner_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_partner_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      orocrm_partner_api_delete_partner
                params:     [ id ]
        sorters:
            columns:
                name:              { data_name: account.name }
                startDate:         { data_name: startDate }
                condition:         { data_name: condition }
                status:            { data_name: status }
                ownerName:         { data_name: ownerName }
                createdAt:         { data_name: account.createdAt }
                updatedAt:         { data_name: account.updatedAt }
            default: { name: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC }
        filters:
            columns:
                name:
                    type:      string
                    data_name: account.name
                startDate:
                    type:      string
                    data_name: startDate
                condition:
                    type:      string
                    data_name: condition
                status:
                    type:      string
                    data_name: status
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: account.createdAt
                updatedAt:
                    type:      datetime
                    data_name: account.updatedAt
        actions:
            view:
                type:          navigate
                acl_resource:  orocrm_partner_view
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  orocrm_partner_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  orocrm_partner_delete
                label:         Delete
                icon:          trash
                link:          delete_link
        mass_actions:
            delete:
                type: delete
                entity_name: %orocrm_partner.partner.entity.class%
                data_identifier: partner.id
                acl_resource: orocrm_contact_delete
                label: orocrm.partner.datagrid.delete
                icon: trash
