oro_menu_config:
    items:
        partner_list:
            label: 'orocrm.partner.entity_plural_label'
            route: 'orocrm_partner_index'
            extras:
                position: 50
                routes: ['orocrm_partner_*']
                description: 'orocrm.parnter.menu.partner_list.description'

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        partner_list: ~
