parameters:
    # Entity
    orocrm_partner.partner.entity.class:                        OroCRM\Bundle\PartnerBundle\Entity\Partner
    orocrm_partner.partner.github_account.entity.class:         OroCRM\Bundle\PartnerBundle\Entity\GitHubAccount
    orocrm_partner.partner.github_issue.entity.class:           OroCRM\Bundle\PartnerBundle\Entity\GitHubIssue

    # Manager
    orocrm_partner.partner.manager.api.class:                   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    # Validator
    orocrm_partner.validator.unique_partner_account.class:      OroCRM\Bundle\PartnerBundle\Validator\Constraints\UniquePartnerAccountValidator

    # Config provider
    orocrm_partner.provider.configuration.class:                OroCRM\Bundle\PartnerBundle\Provider\ConfigurationProvider

    # GitHub integration
    orocrm_partner.github.client_factory.class:                 OroCRM\Bundle\PartnerBundle\Model\GitHubClientFactory
    orocrm_partner.github.collaborator_manager.class:           OroCRM\Bundle\PartnerBundle\Model\GitHubCollaboratorManager

    # Process actions
    orocrm_partner.action.add_collaborator.class:               OroCRM\Bundle\PartnerBundle\Model\Action\AddCollaborator
    orocrm_partner.action.remove_collaborator.class:            OroCRM\Bundle\PartnerBundle\Model\Action\RemoveCollaborator

    # Activity
    orocrm_partner.activity_list.provider.class:                OroCRM\Bundle\PartnerBundle\Provider\GitHubIssueActivityListProvider

services:
    # Api Manager
    orocrm_partner.partner.manager.api:
        class: %orocrm_partner.partner.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %orocrm_partner.partner.entity.class%
            - @doctrine.orm.entity_manager

    # Validator
    orocrm_partner.validator.unique_partner_account:
        class: %orocrm_partner.validator.unique_partner_account.class%
        arguments:
            - @doctrine
        tags:
            - { name: validator.constraint_validator, alias: unique_partner_account }

    # Config provider
    orocrm_partner.provider.configuration:
        class: %orocrm_partner.provider.configuration.class%
        arguments:
            - @oro_config.global

    # GitHub integration
    orocrm_partner.github.client_factory:
        class: %orocrm_partner.github.client_factory.class%

    orocrm_partner.github.collaborator_manager:
        class: %orocrm_partner.github.collaborator_manager.class%
        arguments:
            - @orocrm_partner.provider.configuration
            - @orocrm_partner.github.client_factory

    # Process actions
    orocrm_partner.action.add_collaborator:
        class: %orocrm_partner.action.add_collaborator.class%
        arguments:
            - @oro_workflow.context_accessor
            - @orocrm_partner.github.collaborator_manager
        tags:
            - { name: oro_workflow.action, alias: orocrm_partner_add_github_collaborator }

    orocrm_partner.action.remove_collaborator:
        class: %orocrm_partner.action.remove_collaborator.class%
        arguments:
            - @oro_workflow.context_accessor
            - @orocrm_partner.github.collaborator_manager
        tags:
            - { name: oro_workflow.action, alias: orocrm_partner_remove_github_collaborator }

    # Activity
    orocrm_partner.activity_list.provider:
        class: %orocrm_partner.activity_list.provider.class%
        arguments:
           - @oro_entity.doctrine_helper
        tags:
           - { name: oro_activity_list.provider }
