oro_system_configuration:
    groups:
        oro_crm_partner_settings:
            title: 'orocrm.partner.system_configuration.groups.partner_settings'
        github_integration:
            title: 'orocrm.partner.system_configuration.groups.github_integration'
        github_connection:
            title: 'orocrm.partner.system_configuration.groups.github_connection'
    fields:
        oro_crm_partner.github_api_token:
            type: text
            data_type: string
            options:
                label: 'orocrm.partner.system_configuration.api_token'
                resettable: false
                tooltip: 'orocrm.partner.system_configuration.api_token.tooltip'

        oro_crm_partner.github_organization:
            type: text
            data_type: string
            options:
                label: 'orocrm.partner.system_configuration.organization'
                resettable: false
                tooltip: 'orocrm.partner.system_configuration.organization.tooltip'

        oro_crm_partner.github_teams:
            type: textarea
            data_type: string
            options:
                label: 'orocrm.partner.system_configuration.teams'
                resettable: false
                tooltip: 'orocrm.partner.system_configuration.teams.tooltip'

    tree:
        system_configuration:
            platform:
                children:
                    oro_crm_partner_settings:
                        priority: 255
                        children:
                            github_integration:
                                children:
                                    github_connection:
                                        children:
                                            - oro_crm_partner.github_api_token
                                            - oro_crm_partner.github_teams
                                            - oro_crm_partner.github_organization
