oro_system_configuration:
    groups:
        oro_crm_partner_settings:
            title: 'Partner Settings'
        git_hub_integration:
            title: 'GitHub Integration'
        git_hub_connection:
            title: 'Connection'
    fields:
        oro_crm_partner.github_api_token:
            type: text
            options:
                label: 'orocrm.partner.system_configuration.api_token'
                resettable: false
                tooltip: 'orocrm.partner.system_configuration.api_token.tooltip'

        oro_crm_partner.github_repositories:
            type: textarea
            options:
                label: 'orocrm.partner.system_configuration.repositories'
                resettable: false
                tooltip: 'orocrm.partner.system_configuration.repositories.tooltip'

    tree:
        system_configuration:
            platform:
                children:
                    oro_crm_partner_settings:
                        priority: 255
                        children:
                            git_hub_integration:
                                children:
                                    git_hub_connection:
                                        children:
                                            - oro_crm_partner.github_api_token
                                            - oro_crm_partner.github_repositories
