OroCRM\Bundle\PartnerBundle\Entity\Partner:
    properties:
        account:
            - NotBlank: ~
        status:
            - NotBlank: ~
    constraints:
        - OroCRM\Bundle\PartnerBundle\Validator\Constraints\UniquePartnerAccount: ~

OroCRM\Bundle\PartnerBundle\Entity\GitHubAccount:
    properties:
        username:
            - NotBlank: ~
        email:
            - Email: ~

OroCRM\Bundle\PartnerBundle\Entity\GitHubIssue:
    properties:
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        assignedTo:
            - NotBlank:
                message: 'You need to have a GitHub Account assigned to you partner to add a new GitHub issue'
        channel:
            - NotBlank:
                message: 'You need to have a GitHub integration configured to add a new GitHub issue'
