OroCRM\Bundle\PartnerBundle\Entity\Partner:
    properties:
        account:
            - NotBlank: ~
        status:
            - NotBlank: ~
    constraints:
        - OroCRM\Bundle\PartnerBundle\Validator\Constraints\UniquePartnerAccount: ~

OroCRM\Bundle\PartnerBundle\Entity\PartnerGitHub:
    properties:
        username:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        name:
            - NotBlank: ~
