OroCRM\Bundle\PartnerBundle\Entity\Partner:
    properties:
        status:
            - NotBlank: ~
    constraints:
        - OroCRM\Bundle\PartnerBundle\Validator\Constraints\UniquePartnerAccount: ~